name: quizo
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  # Cupertino icons for iOS style
  cupertino_icons: ^1.0.8
  go_router: ^16.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

  # Flutter launcher icons for changing app icon
  flutter_launcher_icons: ^0.11.0

flutter:

  uses-material-design: true

  assets:
    - assets/

flutter_icons:
  android: true
  ios: true
  image_path: "assets/splash.png"
  # Optional adaptive icon for Android
  android_adaptive_icon_background: "#ffffff"
  android_adaptive_icon_foreground: "assets/splash.png"
  remove_alpha_ios: true
